#The game() function in a program lets a user play a game and returns the score
# as an integer. You need to read a file ‘Hi-score.txt’ which is either blank or
# contains the previous Hi-score. You need to write a program to update the Hiscore whenever the game() function breaks the Hi-score.



#to generate number we use random module 

import random

#create game function to play the game

def game():
    print("You are playing the game..")
    score = random.randint(1,70)
    #fetch the hiscore --> uisng random.randint generate random number --> in between 1 and 70
    with open ("hiscore.txt") as f:
        hiscore = f.read()
        #file is opened in read mode by default using read function , 
        if(hiscore != ""):
            hiscore = int(hiscore)
        else:
            hiscore = 0

            #if hiscore not emmpty , that is having some number --> then that hiscore is stored as int datatype
            #as we know txt file has string type of data
            #if is empty , then (only for the first time it has value 0)

    print(f"Your Score : {score}")
    #to print the score generated by random module

    if(score > hiscore):
        #write this score to the file is greater than hiscore 
        with open ("hiscore.txt","w") as f:
            f.write(str(score))

#after the first run --> it stores some non negative value in it , so after comparison of 
#random number and hiscore stored in it, it writes the file 

    return score

game()